<?php
namespace common\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property integer $currency
 * @property integer $wallet_id
 * @property integer $agent_id
 * @property string $name
 * @property string $email
 * @property string $telphone_code
 * @property string $mobile
 * @property string $salt
 * @property string $password
 * @property integer $ranting
 * @property integer $strong
 * @property integer $online
 * @property string $role
 * @property integer $tags
 * @property integer $ip
 * @property string $first_account
 * @property integer $language
 * @property string $invit_code
 * @property string $channel
 * @property integer $login_ip
 * @property integer $last_login
 * @property string $auth_status
 * @property integer $limit_status
 * @property integer $limit_video
 * @property integer $limit_lottery
 * @property integer $state
 * @property integer $lock
 * @property string $created
 * @property string $updated
 */
class User extends BaseModel
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }
    public static function getMain(){
        return Yii::$app->main;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['currency', 'wallet_id', 'agent_id', 'ranting', 'strong', 'online', 'tags', 'ip', 'language', 'login_ip', 'last_login', 'limit_status', 'limit_video', 'limit_lottery', 'state', 'lock'], 'integer'],
            [['wallet_id', 'name', 'salt', 'password'], 'required'],
            [['role', 'channel', 'auth_status'], 'string'],
            [['created', 'updated'], 'safe'],
            [['name', 'mobile'], 'string', 'max' => 50],
            [['email', 'first_account'], 'string', 'max' => 100],
            [['telphone_code'], 'string', 'max' => 20],
            [['salt'], 'string', 'max' => 6],
            [['password'], 'string', 'max' => 32],
            [['invit_code'], 'string', 'max' => 30],
            [['name'], 'unique'],
            [['avatar'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'currency' => 'Currency',
            'wallet_id' => 'Wallet ID',
            'agent_id' => 'Agent ID',
            'name' => 'Name',
            'email' => 'Email',
            'telphone_code' => 'Telphone Code',
            'mobile' => 'Mobile',
            'salt' => 'Salt',
            'password' => 'Password',
            'ranting' => 'Ranting',
            'strong' => 'Strong',
            'online' => 'Online',
            'role' => 'Role',
            'tags' => 'Tags',
            'ip' => 'Ip',
            'first_account' => 'First Account',
            'language' => 'Language',
            'invit_code' => 'Invit Code',
            'channel' => 'Channel',
            'login_ip' => 'Login Ip',
            'last_login' => 'Last Login',
            'auth_status' => 'Auth Status',
            'limit_status' => 'Limit Status',
            'limit_video' => 'Limit Video',
            'limit_lottery' => 'Limit Lottery',
            'state' => 'State',
            'lock' => 'Lock',
            'created' => 'Created',
            'updated' => 'Updated',
        ];
    }

    /**
     * 返回用户头像
     */
    public static function userAvatar($id = 1)
    {
        $avatar = static::avatar();
        foreach ($avatar as $k => $val) {
            if ($val['id'] == $id) {
                return $val['url'];
            }
        }
    }

    /**
     * 头像
     */
    public static function avatar($id = 1)
    {
        $avatar = [
            [
                "id" => 1,
                "url" => "/static/user/photo1.jpg",
                "check" => 0
            ],
            [
                "id" => 2,
                "url" => "/static/user/photo2.jpg",
                "check" => 0
            ],
            [
                "id" => 3,
                "url" => "/static/user/photo3.jpg",
                "check" => 0
            ],
            [
                "id" => 4,
                "url" => "/static/user/photo4.jpg",
                "check" => 0
            ]
        ];
        foreach ($avatar as $k => $val) {
            if ($val['id'] == $id) {
                $avatar[$k]['check'] = 1;
                break;
            }
        }

        return $avatar;
    }
  /**
     * 返回数据库字段信息，仅在生成CRUD时使用，如不需要生成CRUD，请注释或删除该getTableColumnInfo()代码
     * COLUMN_COMMENT可用key如下:
     * label - 显示的label
     * inputType 控件类型, 暂时只支持text,hidden  // select,checkbox,radio,file,password,
     * isEdit   是否允许编辑，如果允许编辑将在添加和修改时输入
     * isSearch 是否允许搜索
     * isDisplay 是否在列表中显示
     * isOrder 是否排序
     * udc - udc code，inputtype为select,checkbox,radio三个值时用到。
     * 特别字段：
     * id：主键。必须含有主键，统一都是id
     * create_date: 创建时间。生成的代码自动赋值
     * update_date: 修改时间。生成的代码自动赋值
     */
    public function getTableColumnInfo(){
        return array(
        'id' => array(
                        'name' => 'id',
                        'allowNull' => false,
//                         'autoIncrement' => true,
//                         'comment' => '用户id',
//                         'dbType' => "int(11) unsigned",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => true,
                        'phpType' => 'integer',
                        'precision' => '11',
                        'scale' => '',
                        'size' => '11',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('id'),
                        'inputType' => 'hidden',
                        'isEdit' => true,
                        'isSearch' => true,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'currency' => array(
                        'name' => 'currency',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '货币',
//                         'dbType' => "int(11) unsigned",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '11',
                        'scale' => '',
                        'size' => '11',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('currency'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'wallet_id' => array(
                        'name' => 'wallet_id',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '#用户主钱包id，对应表funds，在创建用户前生成',
//                         'dbType' => "int(11) unsigned",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '11',
                        'scale' => '',
                        'size' => '11',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('wallet_id'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'agent_id' => array(
                        'name' => 'agent_id',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '代理ID',
//                         'dbType' => "int(11) unsigned",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '11',
                        'scale' => '',
                        'size' => '11',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('agent_id'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'name' => array(
                        'name' => 'name',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '用户名',
//                         'dbType' => "char(50)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '50',
                        'scale' => '',
                        'size' => '50',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('name'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'email' => array(
                        'name' => 'email',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '邮箱',
//                         'dbType' => "char(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('email'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'telphone_code' => array(
                        'name' => 'telphone_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '电话区号',
//                         'dbType' => "varchar(20)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '20',
                        'scale' => '',
                        'size' => '20',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('telphone_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'mobile' => array(
                        'name' => 'mobile',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '手机号',
//                         'dbType' => "char(50)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '50',
                        'scale' => '',
                        'size' => '50',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('mobile'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'salt' => array(
                        'name' => 'salt',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '6位随机字符',
//                         'dbType' => "char(6)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '6',
                        'scale' => '',
                        'size' => '6',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('salt'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'password' => array(
                        'name' => 'password',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '密码(md5(md5(pw)+salt)',
//                         'dbType' => "char(32)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '32',
                        'scale' => '',
                        'size' => '32',
                        'type' => 'char',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('password'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'ranting' => array(
                        'name' => 'ranting',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '用户等级',
//                         'dbType' => "int(11) unsigned",
                        'defaultValue' => '1',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '11',
                        'scale' => '',
                        'size' => '11',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('ranting'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'strong' => array(
                        'name' => 'strong',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '安全等级 默认值0',
//                         'dbType' => "tinyint(2)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '2',
                        'scale' => '',
                        'size' => '2',
                        'type' => 'smallint',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('strong'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'online' => array(
                        'name' => 'online',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '状态(1在线，0离线)',
//                         'dbType' => "tinyint(3)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '3',
                        'scale' => '',
                        'size' => '3',
                        'type' => 'smallint',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('online'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'role' => array(
                        'name' => 'role',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '角色',
//                         'dbType' => "enum('normal','rotot','test')",
                        'defaultValue' => 'normal',
                        'enumValues' => ["normal","rotot","test"],
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('role'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'tags' => array(
                        'name' => 'tags',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '标记',
//                         'dbType' => "int(11)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '11',
                        'scale' => '',
                        'size' => '11',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('tags'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'ip' => array(
                        'name' => 'ip',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '注册ip',
//                         'dbType' => "int(10) unsigned",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '10',
                        'scale' => '',
                        'size' => '10',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('ip'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'first_account' => array(
                        'name' => 'first_account',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '首选账户',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('first_account'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'language' => array(
                        'name' => 'language',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '语言',
//                         'dbType' => "tinyint(3) unsigned",
                        'defaultValue' => '1',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '3',
                        'scale' => '',
                        'size' => '3',
                        'type' => 'smallint',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('language'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'invit_code' => array(
                        'name' => 'invit_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '推荐码',
//                         'dbType' => "varchar(30)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '30',
                        'scale' => '',
                        'size' => '30',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('invit_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'channel' => array(
                        'name' => 'channel',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '注册方式 @t:h5, pc,app,reserved =其它',
//                         'dbType' => "enum('pc','reserved','h5','app')",
                        'defaultValue' => '',
                        'enumValues' => ["pc","reserved","h5","app"],
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('channel'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'login_ip' => array(
                        'name' => 'login_ip',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '上次登录ip',
//                         'dbType' => "int(10) unsigned",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '10',
                        'scale' => '',
                        'size' => '10',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('login_ip'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'last_login' => array(
                        'name' => 'last_login',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '上次登入',
//                         'dbType' => "int(10) unsigned",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '10',
                        'scale' => '',
                        'size' => '10',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('last_login'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'auth_status' => array(
                        'name' => 'auth_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => 'refuse_withdraw(禁止提款),refuse_sale(禁止优惠),refuse_rebate(禁止返水)',
//                         'dbType' => "set('refuse_withdraw','refuse_sale','refuse_rebate')",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '0',
                        'scale' => '0',
                        'size' => '0',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('auth_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'limit_status' => array(
                        'name' => 'limit_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '自我登录限制状态(1是,0否)',
//                         'dbType' => "tinyint(3)",
                        'defaultValue' => '1',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '3',
                        'scale' => '',
                        'size' => '3',
                        'type' => 'smallint',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('limit_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'limit_video' => array(
                        'name' => 'limit_video',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '视讯盈利限制',
//                         'dbType' => "int(11)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '11',
                        'scale' => '',
                        'size' => '11',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('limit_video'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'limit_lottery' => array(
                        'name' => 'limit_lottery',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '彩票盈利限制',
//                         'dbType' => "int(11)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '11',
                        'scale' => '',
                        'size' => '11',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('limit_lottery'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'state' => array(
                        'name' => 'state',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '账户状态(0禁用1启用2黑名单3删除4封号)',
//                         'dbType' => "tinyint(4)",
                        'defaultValue' => '1',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '4',
                        'scale' => '',
                        'size' => '4',
                        'type' => 'smallint',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('state'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'lock' => array(
                        'name' => 'lock',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '层级锁定',
//                         'dbType' => "tinyint(3)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '3',
                        'scale' => '',
                        'size' => '3',
                        'type' => 'smallint',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('lock'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'created' => array(
                        'name' => 'created',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('created'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'updated' => array(
                        'name' => 'updated',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '最后更新时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('updated'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		        );
        
    }
 
}
